#!/bin/bash

scriptDir=$HOME/Documents/projects/scripts/theme-switch-arch/allThemes

echo "selected $1"

if [[  "$1" == "Reading" ]]; then
  # source "$scriptDir/colors/reading.colors"
  "${scriptDir}/waybar_theme.sh" "00reading"
  # "${scriptDir}/waybar_theme.sh" "gruvbox-dark"
  "${scriptDir}/rofi_theme.sh" "gruvbox-dark"
  "${scriptDir}/cava_switch.sh" "tricolor"
  # "${scriptDir}/kitty_switch.sh" "catppuccin-Latte"
  # "${scriptDir}/kitty_switch.sh" "Leaf Light"
  "${scriptDir}/kitty_switch.sh" "E-Ink"
  "${scriptDir}/hypr_switch.sh" "03_reading"
  "${scriptDir}/wallpaper_switcher.sh" "reading_6.jpg" "reading_5.jpg"
elif [[ "$1" == "workout" ]]; then
  "${scriptDir}/waybar_theme.sh" "mugetsu"
  "${scriptDir}/rofi_theme.sh" "mugetsu"
  "${scriptDir}/cava_switch" "frappe"
  "${scriptDir}/kitty_switch.sh" "catppuccin-Latte"
  "${scriptDir}/hypr_switch.sh" "mugetsu"
  "${scriptDir}/wallpaper_switcher.sh" "workout_01.png" "aura_01.png"

elif [[ "$1" == "default mode" ]]; then
  "${scriptDir}/waybar_theme.sh" "Vclassic_minimal"
  "${scriptDir}/rofi_theme.sh" "current"
  "${scriptDir}/cava_switch.sh" "solarized_dark"
  "${scriptDir}/kitty_switch.sh" "Apprentice"
  "${scriptDir}/hypr_switch.sh" "default"
  "${scriptDir}/wallpaper_switcher.sh" "$HOME/.cache/current_wallpaper" "$HOME/.cache/current_wallpaper_hdmi"
elif [[  "$1" == "devops" ]]; then
  # source "$scriptDir/colors/reading.colors"
  "${scriptDir}/waybar_theme.sh" "00reading"
  # "${scriptDir}/waybar_theme.sh" "gruvbox-dark"
  "${scriptDir}/rofi_theme.sh" "gruvbox-dark"
  "${scriptDir}/cava_switch.sh" "tricolor"
  # "${scriptDir}/kitty_switch.sh" "catppuccin-Latte"
  # "${scriptDir}/kitty_switch.sh" "Leaf Light"
  "${scriptDir}/kitty_switch.sh" "E-Ink"
  "${scriptDir}/hypr_switch.sh" "03_reading"
  "${scriptDir}/wallpaper_switcher.sh" "reading_6.jpg" "reading_5.jpg"
elif [[  "$1" == "project" ]]; then
  # source "$scriptDir/colors/reading.colors"
  "${scriptDir}/waybar_theme.sh" "00reading"
  # "${scriptDir}/waybar_theme.sh" "gruvbox-dark"
  "${scriptDir}/rofi_theme.sh" "gruvbox-dark"
  "${scriptDir}/cava_switch.sh" "tricolor"
  # "${scriptDir}/kitty_switch.sh" "catppuccin-Latte"
  # "${scriptDir}/kitty_switch.sh" "Leaf Light"
  "${scriptDir}/kitty_switch.sh" "E-Ink"
  "${scriptDir}/hypr_switch.sh" "03_reading"
  "${scriptDir}/wallpaper_switcher.sh" "reading_6.jpg" "reading_5.jpg"
elif [[  "$1" == "project" ]]; then
  # source "$scriptDir/colors/reading.colors"
  "${scriptDir}/waybar_theme.sh" "00reading"
  # "${scriptDir}/waybar_theme.sh" "gruvbox-dark"
  "${scriptDir}/rofi_theme.sh" "gruvbox-dark"
  "${scriptDir}/cava_switch.sh" "tricolor"
  # "${scriptDir}/kitty_switch.sh" "catppuccin-Latte"
  # "${scriptDir}/kitty_switch.sh" "Leaf Light"
  "${scriptDir}/kitty_switch.sh" "E-Ink"
  "${scriptDir}/hypr_switch.sh" "03_reading"
  "${scriptDir}/wallpaper_switcher.sh" "reading_6.jpg" "reading_5.jpg"
elif [[  "$1" == "tired" ]]; then
  # source "$scriptDir/colors/reading.colors"
  "${scriptDir}/waybar_theme.sh" "00reading"
  # "${scriptDir}/waybar_theme.sh" "gruvbox-dark"
  "${scriptDir}/rofi_theme.sh" "gruvbox-dark"
  "${scriptDir}/cava_switch.sh" "tricolor"
  # "${scriptDir}/kitty_switch.sh" "catppuccin-Latte"
  # "${scriptDir}/kitty_switch.sh" "Leaf Light"
  "${scriptDir}/kitty_switch.sh" "E-Ink"
  "${scriptDir}/hypr_switch.sh" "03_reading"
  "${scriptDir}/wallpaper_switcher.sh" "reading_6.jpg" "reading_5.jpg"
fi
elif [[  "$1" == "communication" ]]; then
  # source "$scriptDir/colors/reading.colors"
  "${scriptDir}/waybar_theme.sh" "00reading"
  # "${scriptDir}/waybar_theme.sh" "gruvbox-dark"
  "${scriptDir}/rofi_theme.sh" "gruvbox-dark"
  "${scriptDir}/cava_switch.sh" "tricolor"
  # "${scriptDir}/kitty_switch.sh" "catppuccin-Latte"
  # "${scriptDir}/kitty_switch.sh" "Leaf Light"
  "${scriptDir}/kitty_switch.sh" "E-Ink"
  "${scriptDir}/hypr_switch.sh" "03_reading"
  "${scriptDir}/wallpaper_switcher.sh" "reading_6.jpg" "reading_5.jpg"
fi
# "${scriptDir}/cava_switch" "frappe.cava"
# "${scriptDir}/rofi_theme.sh" "gruvbox-light"
# "${scriptDir}/kitty_switch.sh" "Ayu"
